server:
  port: 9002

spring:

  cloud: #zookeeper  替代eureka
    zookeeper:
      connect-string: 10.0.0.133:2181,10.0.0.133:2182,10.0.0.133:2183
      discovery:
        enabled: true
        register: true
    loadbalancer:
      retry:
        enabled: true #关闭ribbon自带的retry



  application:
    name: mafeng-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mafeng_orders?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: admin

# MyBatisPlus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名


feign:
  client:
    config:
      mafeng-user: # 这里是指定对mafeng-user这个服务进行调整的。若想变成全局的，就要把mafeng-user变成default
        loggerLevel: FULL  #日志级别


#eureka:
#  client:
#    service-url:
#      defaultZone: http://dom:admin@localhost:8761/myeureka/eureka
#      #defaultZone: http://dom:admin@localhost:8761/myeureka/eureka,http://dom:admin@localhost:8762/myeureka/eureka,http://dom:admin@localhost:8763/myeureka/eureka